### PR TITLE
Upload Document issue resolved

### PR DESCRIPTION
**Pull request by Dhruv80576**
@manjit-hub   issue #30 resolved 
Attached screenshots for confirmation
image
image
image

### CODE REVIEW

**Comment by mjkoder** [comment]
Hey @Dhruv80576, as I can see uploaded files are stored in local device. It was expected that it should be stored in Cloudinary Database.

**Comment by mjkoder** [comment]
Hey @Dhruv80576 I just rechecked and happy to share that I am accepting your pr. Good work !! Sorry I had some doubts.

**Comment by mjkoder** [comment]
image

Still getting this error. Can you raise another issue again and look into it ?

image

**Comment by Dhruv80576** [comment]
@manjit-hub 
Sure i will look into it by eod.

**Comment by mjkoder** [comment]
@Dhruv80576 look issue #51

**Pull request merged**
