### PR TITLE
Added Animations in HomePage

### PR DESCRIPTION
**Pull request by anmol-284**
Hey I have added Animations on Landing Page. 
Please have a look at it.

Uploading Screen-Recording.mp4…

### CODE REVIEW

**Comment by mjkoder** [comment]
@anmol-284 can you re uplaod video and preview it before sending.

**Comment by anmol-284** [comment]
https://github.com/user-attachments/assets/501e30f7-b0af-4fee-8972-963eeb29a769

Please add hacktoberfest and gssoc ext-24 label

**Comment by mjkoder** [comment]
gssoc ext-24 ??

**Comment by anmol-284** [comment]
Ignore it.

**Pull request merged**
