### PR TITLE
added jwt. removed phone no. fixed sign up

### PR DESCRIPTION
**Pull request by Bluesparx**
HI @manjit-hub, #22  is fixed, I added a middleware for `upload to cloudinary` . Also, I added JWT authentication so make sure everyone adds there JWT_SECRET in the .env file.

### CODE REVIEW

**Review by mjkoder — CHANGES_REQUESTED** [review]
seems good, but as I can see you have removed importing 'express' and 'dotenv' from each file. I think you should not remove package import. It might cause error. Can you please add them back.

**Comment by Bluesparx** [comment]
Yes  I agree. I'll add express. for dotenv I added a file constants.js which doesn't cause an issue and we won't need to import dotenv in each file if we use this. Should I remove it and add the imports back to it's place.

**Comment by mjkoder** [comment]
Oh if it works like that then let it be. If any conflicts/error arises then I will let you know.
Good work !!

**Comment by Bluesparx** [comment]
Thankyou!

**Pull request merged**
