### PR TITLE
Added the google sign-in/sign-up buttons and default pfp

### PR DESCRIPTION
**Pull request by shawaiz-khan**
**What’s New:**

1. Google Sign-In/Sign-Up Buttons: Added buttons for users to easily sign in or sign up using their Google accounts.
2. Default Profile Picture: If a user hasn’t uploaded a profile picture, a default image will now be shown.

**Why This Matters:**

1. Easier Login: The Google buttons make it quicker and easier for users to access their accounts.
2. Consistent Profiles: The default profile picture helps keep the user interface looking clean and uniform.

### CODE REVIEW

**Comment by shawaiz-khan** [comment]
Related to #36 (Frontend)

**Comment by mjkoder** [comment]
@shawaiz-khan it should be functioning. But you just added button. Can you add functionality too. You have to add auth part too. Work on server side and API.

**Comment by shawaiz-khan** [comment]
image
???

**Comment by mjkoder** [comment]
@shawaiz-khan clearely mentioned 'functionality' also + priority high set.

**Comment by shawaiz-khan** [comment]
Then also provide me .env file, if you want functionality to be setup via your database or should I use google cloud?

**Comment by mjkoder** [comment]
I have added necessary .env for the moment. Setup that. And for Authentication use google authO and use .env where keep your AutoO details I will update that with mine while deploy it.

**Pull request closed without merging**
