### PR TITLE
Theme Button/UI improvement

### PR DESCRIPTION
**Pull request by anuj-pal27**
I had created a theme toggle button top at the header and also improve some errors in tailwind css and added a new feature of password show in text and created a button .

### CODE REVIEW

**Comment by mjkoder** [comment]
can you also share screen of changes you made?

**Comment by anuj-pal27** [comment]
@manjit-hub  sure!, here it is -->
Screenshot from 2024-10-02 12-37-20
Screenshot from 2024-10-02 12-36-32

**Comment by anuj-pal27** [comment]
Screenshot from 2024-10-02 12-39-32

**Comment by anuj-pal27** [comment]
also updated UI in /upload , /profile 
Screenshot from 2024-10-02 12-43-29
Screenshot from 2024-10-02 12-43-05

**Comment by mjkoder** [comment]
@anuj-pal27 
There are several issues:
1. You made the logo to shift right, which is not required.
2. Make some difference in color between Header and Body and Footer, while changing theme.
3. No need to show 'Dark' or 'Light' in toggle. Remove text.
4. Place the toggle button just before 'Home' button instead placing at end.
5. Resize Toggle button according to rest elements.
6. Change theme of login and signup form, which should change according to theme.

7. Note: Dont go deep into changing signup and login page. Other contributors are working on it. You just work on theme part.

Please go through each mentioned points. 
No need to rush, take time and make perfect.

**Comment by anuj-pal27** [comment]
@manjit-hub  thank you for mentioning , I will work on it !

**Comment by anuj-pal27** [comment]
@manjit-hub  i had correct the previous problems in UI that you mentioned, here how it looks like -->
Screenshot from 2024-10-02 21-41-53
Screenshot from 2024-10-02 21-41-41
Screenshot from 2024-10-02 21-41-32

should i make a pull requrest????

**Comment by mjkoder** [comment]
@anuj-pal27 
image
Move these components. Also Header theme is not changing with theme change. Make sure that it changes with theme changes. Keep it what it's now for dark theme. Add some different bg color for light theme.

**Comment by anuj-pal27** [comment]
@manjit-hub Changing the bg color only for header or for a body also ??

**Comment by mjkoder** [comment]
@anuj-pal27 for light theme only change header.

**Comment by anuj-pal27** [comment]
@manjit-hub updated UI --->
Screenshot from 2024-10-02 22-47-43
Screenshot from 2024-10-02 22-47-36

**Comment by anuj-pal27** [comment]
@manjit-hub updated UI--->
Screenshot from 2024-10-02 22-51-17
Screenshot from 2024-10-02 22-51-10

**Comment by anuj-pal27** [comment]
@manjit-hub  
Screenshot from 2024-10-02 22-57-10
Screenshot from 2024-10-02 22-57-02
updated UI --->

**Comment by mjkoder** [comment]
There is still distortion in header. Dont rush @anuj-pal27 .I respect your efforts but for the moment I am closing this pr.image

**Comment by anuj-pal27** [comment]
@manjit-hub  sorry for the inconvenience, i will improve it and make it better.

**Pull request merged**
