### PR TITLE
feat: init shadcn ui

### PR DESCRIPTION
**Pull request by rahulxdemon**
I have add shadcn ui support and a jsconfig.json file for shadcn config

### CODE REVIEW

**Comment by mjkoder** [comment]
Can you share ss ?

**Comment by rahulxdemon** [comment]
I have completed the theme toggle button as you said and also changed the `bg` and `text` color for dynamic theme

Here are the ss
Dark theme:
image

Light Theme:
image

**Comment by mjkoder** [comment]
hey @rahulpeacock, I have recently merged someones pr and hence getting conflict with your pr. Also he has resolved the toggle button and theme part. Can you revise the current updated repo and try to make it better ?

**Comment by rahulxdemon** [comment]
Ok

**Comment by rahulxdemon** [comment]
@manjit-hub I have solved the merge conflicts.

**Comment by mjkoder** [comment]
Sorry @rahulpeacock, I think recently added toggle is better than yours. So I can't merge yours. But good effort !!

**Pull request closed without merging**
